apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test-deploy
  labels:
    app: hello-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-test
  template:
    metadata:
      labels:
        app: hello-test
    spec:
      containers:
      - name: hello-test
        image: arunkumartocloud/hello-test:hello-test
---
apiVersion: v1
kind: Service
metadata:
  name: hello-test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: hello-test
